### ISSUE TITLE
should add curl sample for usage of token

### ISSUE THREAD

**Issue by jmichler** [Entwicklung-AvaL-Standard/oauth2-samples#12]
The curl samples are great to get and verify a bearer token. I think however it would be helpful to also have a sample call where the bearer token is then used. 
Probably it is just:
Authorization: Bearer XYZ

but I find that nowhere here in the curl samples nor in the samples https://www.avalstandard.de/files/content/downloads/aval-standard-teil-4-webservices/AvaL_Projekt_1_Technisches_Konzept_V1.5.pdf or in https://www.avalstandard.de/files/content/downloads/teil4-webservices-objekte-funktionen/AvaL%20Standard%20Teil%204.3%20Webservice%20und%20Serverdienste%20Partnerverzeichnis%20und%20Authentifizierung%202022-03-09.pdf

@curban111 what do you think?

**Comment by curban111** [comment]
You're right, we didn't add the example of using the token. I'll add one.
